vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|15 Dec 1998 03:11:44 -0000
vti_author:SR|Marcos Alves
vti_modifiedby:SR|Marcos Alves
vti_timecreated:TR|03 Mar 2005 22:06:14 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.2717
vti_version:SW|4.0.2.2717
vti_syncwith_ftp.planeta.terra.com.br\:21:TR|03 Mar 2005 22:06:16 -0000
vti_syncofs_ftp.planeta.terra.com.br\:21:TW|07 Mar 2005 22:25:00 -0000
vti_syncwith_ftp.hpg.com.br\:21:TR|03 Mar 2005 22:06:16 -0000
vti_syncofs_ftp.hpg.com.br\:21:TW|22 Mar 2005 01:04:00 -0000
vti_nexttolasttimemodified:TW|15 Dec 1998 03:11:44 -0000
